package com.example.mooderation.auth.base;

/**
 * Wraps errors generated by an IAuthenticator.
 *
 * TODO: need to subclass this for each error type, e.g. InvalidEmailAuthenticationError, etc.
 */
public class AuthenticationError {
}
